apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pipeline-example
parameters:
- name: NAMESPACE
  value: namespace
- name: WEBHOOK_BRANCH
  value: main
- name: WEBHOOK_SECRET
  value: QUADSolutions
- name: APP_NAME
  value: demo-tuesday

labels:
  template: ${APP_NAME}

objects:
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: ${APP_NAME}
  spec:
    params:
    - name: git-url
      type: string
    - name: git-branch
      type: string
    workspaces:
    - name: code-clone

    tasks:
    # fetch-repo
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: code-clone
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-branch)

    - name: test-build
      runAfter:
      - fetch-repo
      workspaces:
      - name: source
        workspace: code-clone
      taskSpec:
        steps:
        - name: test
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          script: |
            #!/usr/bin/env bash
            echo "---- Run Tests  ----"
            cat /workspace/source/index.php
            echo "---- Finished Tests ----"

        - name: build
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          script: |
            #!/usr/bin/env bash
            echo "---- Trigger Build ----"
            oc start-build bc/${APP_NAME}
            echo "---- Finished Build ----"

    finally: 
    - name: final
      taskSpec:
        steps:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          script: |
            #!/usr/bin/env bash
            
            echo "Everything Finished"

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: build-bot 

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: rolebinding-build-bot
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: build-bot
    namespace: ${NAMESPACE}

- apiVersion: triggers.tekton.dev/v1beta1
  kind: TriggerBinding
  metadata:
    name: ${APP_NAME}-trigger-binding
  spec:
    params:
    - name: git-repo-url
      value: $(body.repository.url)

- apiVersion: triggers.tekton.dev/v1beta1
  kind: TriggerTemplate
  metadata:
    name: ${APP_NAME}-trigger-template
  spec:
    params:
    - name: git-repo-url
    resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipeline-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: ${APP_NAME}
        podTemplate:
          securityContext:
            fsGroup: 65532
            runAsUser: 1001
        workspaces:
        - name: code-clone
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        params:
        - name: git-url
          value: https://github.com/FlorentQuad/test-webhook.git
        - name: git-branch
          value: main
      
- apiVersion: triggers.tekton.dev/v1beta1
  kind: Trigger
  metadata:
    name: ${APP_NAME}-trigger
  spec:
    serviceAccountName: pipeline
    interceptors:
      - ref:
          name: "github"
        params:
          - name: "secretRef"
            value:
              secretName: github-secret-webhook
              secretKey: secretToken
          - name: "eventTypes"
            value: ["push"]
      - ref:
          name: "cel"
        params:
          - name: "filter"
            value: body.ref == 'refs/heads/${WEBHOOK_BRANCH}'
    bindings:
      - ref: ${APP_NAME}-trigger-binding
    template:
      ref: ${APP_NAME}-trigger-template

- apiVersion: triggers.tekton.dev/v1beta1
  kind: EventListener
  metadata:
    name: ${APP_NAME}-eventlistener
  spec:
    serviceAccountName: pipeline
    triggers:
      - triggerRef: ${APP_NAME}-trigger
      
- apiVersion: v1
  kind: Secret
  metadata:
    name: github-secret-webhook
  type: Opaque
  stringData:
    secretToken: ${WEBHOOK_SECRET}

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      template: pipeline-${APP_NAME}
    name: el-${APP_NAME}-eventlistener-route
  spec:
    port:
      targetPort: http-listener
    tls:
      insecureEdgeTerminationPolicy: None
      termination: edge
    to:
      kind: Service
      name: el-${APP_NAME}-eventlistener
      weight: 100
    wildcardPolicy: None

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/FlorentQuad/test-webhook
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:8.0-ubi8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: ic5e8M1Qrniip7BwfduZ
      type: GitHub
    - generic:
        secret: juItEuIQgR0xJVYr-Zmq
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"${APP_NAME}:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"${APP_NAME}\")].image"}]'
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: ${APP_NAME}
    template:
      metadata:
        labels:
          deployment: ${APP_NAME}
      spec:
        containers:
        - image: ${APP_NAME}:latest
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: ${APP_NAME}

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${APP_NAME}
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: None
      termination: edge
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
  wildcardPolicy: None
